# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content1', models.TextField()),
                ('content2', models.TextField(blank=True, null=True)),
                ('ref_code', models.TextField(blank=True, null=True)),
                ('github_link', models.TextField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
