# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogContent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Blog_Images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Blog_Images'),
        ),
    ]
