# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogContent', '0002_auto_20171108_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
